### ISSUE TITLE
Impossible to delete about 5k emails with "Delete All" button

### ISSUE THREAD

**Issue by ilkin** [gessnerfl/fake-smtp-server#59]
Couldn't delete about 5k emails with "Delete All". There is memory problem.

```
2022-06-02 12:53:03.795 [http-nio-5080-exec-3          ] WARN  o.h.e.l.i.CollectionLoadContext.cleanup:420        - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [1] entries
2022-06-02 12:53:03.797 [http-nio-5080-exec-3          ] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet].log:175        - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space] with root cause
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:211)
	at org.hibernate.type.descriptor.java.DataHelper.extractBytes(DataHelper.java:190)
	at org.hibernate.type.descriptor.java.PrimitiveByteArrayTypeDescriptor.wrap(PrimitiveByteArrayTypeDescriptor.java:120)
	at org.hibernate.type.descriptor.java.PrimitiveByteArrayTypeDescriptor.wrap(PrimitiveByteArrayTypeDescriptor.java:26)
	at org.hibernate.type.descriptor.sql.BlobTypeDescriptor$1.doExtract(BlobTypeDescriptor.java:48)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243)
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:329)
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3214)
	at org.hibernate.persister.entity.Loadable.hydrate(Loadable.java:94)
	at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.loadFromResultSet(EntityReferenceInitializerImpl.java:342)
	at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.hydrateEntityState(EntityReferenceInitializerImpl.java:269)
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.readRow(AbstractRowReader.java:80)
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractRows(ResultSetProcessorImpl.java:157)
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:94)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:105)
	at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:87)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:710)
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:76)
	at org.hibernate.internal.SessionImpl$$Lambda$1473/0x0000000100b39040.accept(Unknown Source)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:2217)
	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:595)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:264)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:591)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:149)
	at org.hibernate.collection.internal.PersistentBag.iterator(PersistentBag.java:387)
	at org.hibernate.type.CollectionType.getElementsIterator(CollectionType.java:263)
	at org.hibernate.type.CollectionType.getElementsIterator(CollectionType.java:253)
```

**Comment by smuda** [comment]
Did you run it in a container or directly? How much memory did you allocate?

**Comment by ilkin** [comment]
Running as below:
`jdk-11.0.8/bin/java -Xms512m -Xmx1500m -jar fake-smtp-server-1.8.2.jar --spring.config.location=application.properties &`

**Comment by gessnerfl** [comment]
@ilkin The code can be optimized to run the deletion with native queries so that entities are not retrieved from the database. With this the operation should should perform much more memory efficient.

**Comment by gessnerfl** [comment]
@ilkin can you please cross check version 1.8.7. I changed delete all operation in this release to batch deletion. With this emails should not be loaded into the application for deletion. With this memory consumption should be limited.

**Comment by gessnerfl** [comment]
closing the issue after one month without response on the provided solution
